### ISSUE TITLE
Chat history not available in dev version ?

### ISSUE THREAD

**Issue by shanumas** [langchain-ai/chat-langchain#356]
Hi all,
I see that the deployed version has chat history to the left side:

But why the same is not available in the dev version that I foked out and ran locally ?

![image](https://github.com/user-attachments/assets/27281f47-957c-42c0-974e-c0d19e717f4e)

**Comment by vbarda** [comment]
@shanumas could you explain more? are you trying to access chat history from deployed chat langchain but on your local server? if so, that's not possible since the chats are talking to a postgres database that's part of LangGraph server, so the chats persisted in the deployed version can never show up in a local one

and if you're using this branch https://github.com/langchain-ai/chat-langchain/tree/langserve, it does not support chat history (and we don't have plans to support it there)

**Comment by shanumas** [comment]
@vbarda   Sorry.  I am asking about the threads history (see image below).  I use langserve branch.
I see the histor of my previous threads here:  https://chat.langchain.com/ but I do not see it when I 
run the langserve branch.


![image](https://github.com/user-attachments/assets/023972c4-a41e-43a6-8e1b-2b4bb13f2e7a)

**Comment by vbarda** [comment]
@shanumas got it. thread history is not available on langserve branch and we don't have plans to support it there
